blogicum/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_index, name='index'),
    path('posts/<int:pk>/', views.post_detail, name='post_detail'),
    path(
        'category/<slug:category_slug>/',
        views.category_posts,
        name='category_posts'
    ),
]

blogicum/blogicum/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('pages/', include('pages.urls')),
]

blogicum/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.about, name='about'),
    path('rules/', views.rules, name='rules'),
]

blogicum/blog/models.py
# from django.db import models

# Create your models here.

blogicum/pages/models.py
# from django.db import models

# Create your models here.

blogicum/blog/views.py
from django.shortcuts import render

posts = [
    {
        'id': 0,
        'location': 'Остров отчаянья',
        'date': '30 сентября 1659 года',
        'category': 'travel',
        'text': '''Наш корабль, застигнутый в открытом море
                страшным штормом, потерпел крушение.
                Весь экипаж, кроме меня, утонул; я же,
                несчастный Робинзон Крузо, был выброшен
                полумёртвым на берег этого проклятого острова,
                который назвал островом Отчаяния.''',
    },
    {
        'id': 1,
        'location': 'Остров отчаянья',
        'date': '1 октября 1659 года',
        'category': 'not-my-day',
        'text': '''Проснувшись поутру, я увидел, что наш корабль сняло
                с мели приливом и пригнало гораздо ближе к берегу.
                Это подало мне надежду, что, когда ветер стихнет,
                мне удастся добраться до корабля и запастись едой и
                другими необходимыми вещами. Я немного приободрился,
                хотя печаль о погибших товарищах не покидала меня.
                Мне всё думалось, что, останься мы на корабле, мы
                непременно спаслись бы. Теперь из его обломков мы могли бы
                построить баркас, на котором и выбрались бы из этого
                гиблого места.''',
    },
    {
        'id': 2,
        'location': 'Остров отчаянья',
        'date': '25 октября 1659 года',
        'category': 'not-my-day',
        'text': '''Всю ночь и весь день шёл дождь и дул сильный
                порывистый ветер. 25 октября.  Корабль за ночь разбило
                в щепки; на том месте, где он стоял, торчат какие-то
                жалкие обломки,  да и те видны только во время отлива.
                Весь этот день я хлопотал  около вещей: укрывал и
                укутывал их, чтобы не испортились от дождя.''',
    },
]


def blog_index(request):
    template = 'blog/index.html'
    context = {'posts': posts[::-1]}  # Инвертируем порядок постов
    return render(request, template, context)


def post_detail(request, pk):
    post = posts[pk]
    template = 'blog/detail.html'
    context = {'post': post}
    return render(request, template, context)


def category_posts(request, category_slug):
    template = 'blog/category.html'
    context = {'category_slug': category_slug}
    return render(request, template, context)

blogicum/pages/views.py
from django.shortcuts import render


def about(request):
    template = 'pages/about.html'
    return render(request, template)


def rules(request):
    template = 'pages/rules.html'
    return render(request, template)

blogicum/templates/blog/category.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %">
    <title>Публикации в категории {{  category_slug  }}</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'blog:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            Блогикум
          </a>
          <ul class="nav  nav-pills">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:index' %}">
                Лента записей
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pages:about' %}">
                О проекте
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pages:rules' %}">
                Наши правила
              </a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <main>
      <div class="container py-5">
        <h1>Публикации в категории {{  category_slug  }}</h1>
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© Блогикум</p>
    </footer>
  </body>
</html>

blogicum/templates/blog/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %">
    <!-- Формируется из локации и даты -->
    <title>Остров отчаянья. 25 октября 1659 года</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'blog:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            Блогикум
          </a>
          <ul class="nav  nav-pills">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:index' %}">
                Лента записей
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pages:about' %}">
                О проекте
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pages:rules' %}">
                Наши правила
              </a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <main>
      <div class="container py-5">
        <article>
          <ul>
            <li>
              Место: {{  post.location  }}
            </li>
            <li>
              Дата: {{  post.date  }}
            </li>
            <li>
              Категория: {{  post.category  }}
            </li>
          </ul>
          <p>
            {{ post.text }}
          </p>
        </article>
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© Блогикум</p>
    </footer>
  </body>
</html>

blogicum/templates/blog/index.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %">
    <title>Лента записей</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'blog:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            Блогикум
          </a>
          <ul class="nav  nav-pills">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'blog:index' %}">
                Лента записей
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pages:about' %}">
                О проекте
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pages:rules' %}">
                Наши правила
              </a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <main>
      <div class="container py-5">
        <h1>Лента записей</h1>
        <!-- Перебираем в цикле все посты -->
        {% for post in posts %}
        <hr>
        <article>
          <ul>
            <li>
              Место: {{  post.location  }}
            </li>
            <li>
              Дата: {{  post.date  }}
            </li>
            <li>
              Категория: <a href="{% url 'blog:category_posts' post.category %}">{{ post.category }}</a>
            </li>
          </ul>
          <!-- Первые 10 слов -->
          <p>
            {{ post.text|truncatewords:10 }}
          </p>
          <a href="{% url 'blog:post_detail' post.id %}">Читать полный текст</a>
        {% endfor %}
        </article>
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© Блогикум</p>
    </footer>
  </body>
</html>

blogicum/templates/pages/about.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %">
    <title>О проекте</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'blog:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inlin e-block align-top" alt="">
            Блогикум
          </a>
          <ul class="nav  nav-pills">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:index' %}">
                Лента записей
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'pages:about' %}">
                О проекте
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pages:rules' %}">
                Наши правила
              </a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <main>
      <div class="container py-5">
        <h1>О проекте</h1>
        <p>
          Блогикум — это дом для творческих людей. Это — сообщество людей, для которых 
          нет грани между ведением блога и дружбой в социальных сетях.
        </p>
        <p>
          Дружба и рассказы о новых, неизведанных впечатлениях — вот
          что вы найдете на нашем ресурсе.  Миллионы блогов по различным темам. 
          Путешествия, политики, развлечения, мода, мода, литература, дизайн и все 
          другие сферы человеческой деятельности.
        </p>
        <p>
          Творчество, разнообразие и свобода взглядов и самовыражения —
          основные черты наших пользователей.
        </p>
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© Блогикум</p>
    </footer>
  </body>
</html>

blogicum/templates/pages/rules.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %">
    <title>Наши правила</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'blog:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            Блогикум
          </a>
          <ul class="nav  nav-pills">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:index' %}">
                Лента записей
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pages:about' %}">
                О проекте
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'pages:rules' %}">
                Наши правила
              </a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <main>
      <div class="container py-5">
        <h1>Наши правила</h1>
        <p>
          <b>Cамовыражение.</b> У наших пользователей должна
          быть возможность создать что-то своё, выразить себя,
          свои мысли и чувства.
        </p>
        <p>
          <b>Многообразие.</b> Мы уважаем и приветствуем разные
          мнения и культуры. Блогикум — это место, объединяющее
          самых разных людей. Поделитесь своим уникальным взглядом на мир.
        </p>
        <p>
          <b>Творчество.</b> Не важно, в какой области вы творите,
          это может быть литература, дизайн, программирование.
          Наши инструменты помогут вам раскрыть талант максимально
          просто и комфортно.
        </p>
        <p>
          <b>Личность.</b> Мы сохраним ваши сокровенные мысли в тайне.
          Делитесь своей информацией только с теми, кого выбрали.
          Как и насколько засекречивать вашу личную информацию —
          определяете вы и только вы.
        </p>
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© Блогикум</p>
    </footer>
  </body>
</html>